# Autogenerated wrapper script for PRIMME_jll for x86_64-w64-mingw32
export libprimme

using OpenBLAS_jll
using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("PRIMME")
JLLWrappers.@declare_library_product(libprimme, "libprimme.dll")
function __init__()
    JLLWrappers.@generate_init_header(OpenBLAS_jll, CompilerSupportLibraries_jll)
    JLLWrappers.@init_library_product(
        libprimme,
        "bin\\libprimme.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
